from typing import Any

from io_gen.tables import _signal_is_differential, _signal_is_scalar

# Set of tristate buffers that will require '_i', '_o', and '_t' in the signal
# block and IO ring instances
TRISTATE_BUFFERS = {"iobuf"}

VLOG_DIRECTIONS = {"in": "input", "out": "output", "inout": "inout"}
VHDL_DIRECTIONS = {"in": "in", "out": "out", "inout": "inout"}


def _get_ioring_header() -> list[str]:
    """Language-agnostic list of strings to use as the IO ring header"""
    return [
        "",
        "Generated by io-gen - do not edit",
        "Regenerate from source YAML using io-gen",
        "",
    ]


def _get_signal_top_ports(sig: dict[str, Any]) -> list[dict]:
    """Language-agnostic list of ports for the top level RTL for a given signal"""

    port_base = {
        "direction": sig["direction"],
        "width": sig["width"],
        "is_bus": not _signal_is_scalar(sig),
    }

    port_list = []
    if _signal_is_differential(sig):
        port_list.append({**port_base, "name": f"{sig['name']}_p"})
        port_list.append({**port_base, "name": f"{sig['name']}_n"})
    else:
        port_list.append({**port_base, "name": f"{sig['name']}_pad"})

    return port_list


def _get_signal_nets(sig: dict[str, Any]) -> list[dict]:
    """Language-agnostic list of nets from the IO ring to fabric-facing logic for a given signal"""

    net_base = {
        "width": sig["width"],
        "is_bus": not _signal_is_scalar(sig),
    }

    net_list = []
    if sig["buffer"] not in TRISTATE_BUFFERS:
        net_list.append({**net_base, "name": sig["name"]})
    else:
        net_list.append({**net_base, "name": f"{sig['name']}_i"})
        net_list.append({**net_base, "name": f"{sig['name']}_o"})
        net_list.append({**net_base, "name": f"{sig['name']}_t"})

    return net_list


def _get_signal_ioring_ports(sig: dict[str, Any]) -> list[dict]:
    """Language-agnostic list of ports for IO ring RTL for a given siganl"""

    port_base = {
        "direction": sig["direction"],
        "width": sig["width"],
        "is_bus": not _signal_is_scalar(sig),
    }

    # No bypassed signals in the IO ring.
    if sig["bypass"]:
        return []

    port_list = []
    if _signal_is_differential(sig):
        if sig["direction"] == "in":
            port_list.append({**port_base, "name": f"{sig['name']}_p"})
            port_list.append({**port_base, "name": f"{sig['name']}_n"})
            port_list.append({**port_base, "name": sig["name"], "direction": "out"})
        elif sig["direction"] == "out":
            port_list.append({**port_base, "name": f"{sig['name']}_p"})
            port_list.append({**port_base, "name": f"{sig['name']}_n"})
            port_list.append({**port_base, "name": sig["name"], "direction": "in"})
        else:
            port_list.append({**port_base, "name": f"{sig['name']}_p"})
            port_list.append({**port_base, "name": f"{sig['name']}_n"})
            port_list.append(
                {**port_base, "name": f"{sig['name']}_i", "direction": "out"}
            )
            port_list.append(
                {**port_base, "name": f"{sig['name']}_o", "direction": "in"}
            )
            port_list.append(
                {**port_base, "name": f"{sig['name']}_t", "direction": "in"}
            )
    else:
        if sig["direction"] == "in":
            port_list.append({**port_base, "name": f"{sig['name']}_pad"})
            port_list.append({**port_base, "name": sig["name"], "direction": "out"})
        elif sig["direction"] == "out":
            port_list.append({**port_base, "name": f"{sig['name']}_pad"})
            port_list.append({**port_base, "name": sig["name"], "direction": "in"})
        else:
            port_list.append({**port_base, "name": f"{sig['name']}_pad"})
            port_list.append(
                {**port_base, "name": f"{sig['name']}_i", "direction": "out"}
            )
            port_list.append(
                {**port_base, "name": f"{sig['name']}_o", "direction": "in"}
            )
            port_list.append(
                {**port_base, "name": f"{sig['name']}_t", "direction": "in"}
            )

    return port_list
