set_property PACKAGE_PIN W5 [get_ports clk_100m00_pad]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100m00_pad]

set_property PACKAGE_PIN V17 [get_ports {slider_sw_pad[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slider_sw_pad[0]}]
set_property PACKAGE_PIN V16 [get_ports {slider_sw_pad[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slider_sw_pad[1]}]
set_property PACKAGE_PIN W16 [get_ports {slider_sw_pad[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slider_sw_pad[2]}]
set_property PACKAGE_PIN W17 [get_ports {slider_sw_pad[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slider_sw_pad[3]}]
set_property PACKAGE_PIN W15 [get_ports {slider_sw_pad[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slider_sw_pad[4]}]
set_property PACKAGE_PIN V15 [get_ports {slider_sw_pad[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slider_sw_pad[5]}]
set_property PACKAGE_PIN W14 [get_ports {slider_sw_pad[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slider_sw_pad[6]}]
set_property PACKAGE_PIN W13 [get_ports {slider_sw_pad[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slider_sw_pad[7]}]
set_property PACKAGE_PIN V2 [get_ports {slider_sw_pad[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slider_sw_pad[8]}]
set_property PACKAGE_PIN T3 [get_ports {slider_sw_pad[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slider_sw_pad[9]}]
set_property PACKAGE_PIN T2 [get_ports {slider_sw_pad[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slider_sw_pad[10]}]
set_property PACKAGE_PIN R3 [get_ports {slider_sw_pad[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slider_sw_pad[11]}]
set_property PACKAGE_PIN W2 [get_ports {slider_sw_pad[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slider_sw_pad[12]}]
set_property PACKAGE_PIN U1 [get_ports {slider_sw_pad[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slider_sw_pad[13]}]
set_property PACKAGE_PIN T1 [get_ports {slider_sw_pad[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slider_sw_pad[14]}]
set_property PACKAGE_PIN R2 [get_ports {slider_sw_pad[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {slider_sw_pad[15]}]

set_property PACKAGE_PIN U16 [get_ports {led_pad[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pad[0]}]
set_property PACKAGE_PIN E19 [get_ports {led_pad[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pad[1]}]
set_property PACKAGE_PIN U19 [get_ports {led_pad[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pad[2]}]
set_property PACKAGE_PIN V19 [get_ports {led_pad[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pad[3]}]
set_property PACKAGE_PIN W18 [get_ports {led_pad[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pad[4]}]
set_property PACKAGE_PIN U15 [get_ports {led_pad[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pad[5]}]
set_property PACKAGE_PIN U14 [get_ports {led_pad[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pad[6]}]
set_property PACKAGE_PIN V14 [get_ports {led_pad[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pad[7]}]
set_property PACKAGE_PIN V13 [get_ports {led_pad[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pad[8]}]
set_property PACKAGE_PIN V3 [get_ports {led_pad[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pad[9]}]
set_property PACKAGE_PIN W3 [get_ports {led_pad[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pad[10]}]
set_property PACKAGE_PIN U3 [get_ports {led_pad[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pad[11]}]
set_property PACKAGE_PIN P3 [get_ports {led_pad[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pad[12]}]
set_property PACKAGE_PIN N3 [get_ports {led_pad[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pad[13]}]
set_property PACKAGE_PIN P1 [get_ports {led_pad[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pad[14]}]
set_property PACKAGE_PIN L1 [get_ports {led_pad[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_pad[15]}]

set_property PACKAGE_PIN W7 [get_ports {seg_pad[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_pad[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg_pad[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_pad[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg_pad[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_pad[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg_pad[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_pad[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg_pad[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_pad[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg_pad[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_pad[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg_pad[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_pad[6]}]

set_property PACKAGE_PIN U2 [get_ports {digit_en_pad[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en_pad[0]}]
set_property PACKAGE_PIN U4 [get_ports {digit_en_pad[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en_pad[1]}]
set_property PACKAGE_PIN V4 [get_ports {digit_en_pad[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en_pad[2]}]
set_property PACKAGE_PIN W4 [get_ports {digit_en_pad[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_en_pad[3]}]

set_property PACKAGE_PIN V7 [get_ports dp_pad]
set_property IOSTANDARD LVCMOS33 [get_ports dp_pad]

set_property PACKAGE_PIN U18 [get_ports {btn_pad[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_pad[0]}]
set_property PACKAGE_PIN T18 [get_ports {btn_pad[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_pad[1]}]
set_property PACKAGE_PIN W19 [get_ports {btn_pad[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_pad[2]}]
set_property PACKAGE_PIN T17 [get_ports {btn_pad[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_pad[3]}]
set_property PACKAGE_PIN U17 [get_ports {btn_pad[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_pad[4]}]

set_property PACKAGE_PIN J3 [get_ports {pmod_jxadc_p[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_jxadc_p[0]}]
set_property PACKAGE_PIN K3 [get_ports {pmod_jxadc_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_jxadc_n[0]}]
set_property PACKAGE_PIN L3 [get_ports {pmod_jxadc_p[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_jxadc_p[1]}]
set_property PACKAGE_PIN M3 [get_ports {pmod_jxadc_n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_jxadc_n[1]}]
set_property PACKAGE_PIN M2 [get_ports {pmod_jxadc_p[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_jxadc_p[2]}]
set_property PACKAGE_PIN M1 [get_ports {pmod_jxadc_n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_jxadc_n[2]}]
set_property PACKAGE_PIN N2 [get_ports {pmod_jxadc_p[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_jxadc_p[3]}]
set_property PACKAGE_PIN N1 [get_ports {pmod_jxadc_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_jxadc_n[3]}]

set_property PACKAGE_PIN G19 [get_ports {vga_red_pad[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red_pad[0]}]
set_property PACKAGE_PIN H19 [get_ports {vga_red_pad[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red_pad[1]}]
set_property PACKAGE_PIN J19 [get_ports {vga_red_pad[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red_pad[2]}]
set_property PACKAGE_PIN N19 [get_ports {vga_red_pad[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red_pad[3]}]

set_property PACKAGE_PIN N18 [get_ports {vga_blue_pad[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue_pad[0]}]
set_property PACKAGE_PIN L18 [get_ports {vga_blue_pad[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue_pad[1]}]
set_property PACKAGE_PIN K18 [get_ports {vga_blue_pad[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue_pad[2]}]
set_property PACKAGE_PIN J18 [get_ports {vga_blue_pad[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue_pad[3]}]

set_property PACKAGE_PIN J17 [get_ports {vga_green_pad[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green_pad[0]}]
set_property PACKAGE_PIN H17 [get_ports {vga_green_pad[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green_pad[1]}]
set_property PACKAGE_PIN G17 [get_ports {vga_green_pad[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green_pad[2]}]
set_property PACKAGE_PIN D17 [get_ports {vga_green_pad[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green_pad[3]}]

set_property PACKAGE_PIN P19 [get_ports vga_hsync_pad]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hsync_pad]

set_property PACKAGE_PIN R19 [get_ports vga_vsync_pad]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vsync_pad]

set_property PACKAGE_PIN B18 [get_ports uart_rx_pad]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx_pad]

set_property PACKAGE_PIN A18 [get_ports uart_tx_pad]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_pad]

set_property PACKAGE_PIN C17 [get_ports ps2_clk_pad]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk_pad]

set_property PACKAGE_PIN B17 [get_ports ps2_data_pad]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data_pad]

set_property PACKAGE_PIN K19 [get_ports spi_cs_n_pad]
set_property IOSTANDARD LVCMOS33 [get_ports spi_cs_n_pad]

set_property PACKAGE_PIN D18 [get_ports spi_sdi_pad]
set_property IOSTANDARD LVCMOS33 [get_ports spi_sdi_pad]

set_property PACKAGE_PIN D19 [get_ports spi_sdo_pad]
set_property IOSTANDARD LVCMOS33 [get_ports spi_sdo_pad]

set_property PACKAGE_PIN G18 [get_ports spi_wp_n_pad]
set_property IOSTANDARD LVCMOS33 [get_ports spi_wp_n_pad]

set_property PACKAGE_PIN F18 [get_ports spi_hld_n_pad]
set_property IOSTANDARD LVCMOS33 [get_ports spi_hld_n_pad]
