//
// Generated by io-gen - do not edit
// Regenerate from source YAML using io-gen
//
module basys3_io //#(
//)
(
    input   wire            clk_100m00_pad,
    output  wire            clk_100m00,
    input   wire [15:0]     slider_sw_pad,
    output  wire [15:0]     slider_sw,
    output  wire [15:0]     led_pad,
    input   wire [15:0]     led,
    output  wire [6:0]      seg_pad,
    input   wire [6:0]      seg,
    output  wire [3:0]      digit_en_pad,
    input   wire [3:0]      digit_en,
    output  wire            dp_pad,
    input   wire            dp,
    input   wire [4:0]      btn_pad,
    output  wire [4:0]      btn,
    input   wire [3:0]      pmod_jxadc_p,
    input   wire [3:0]      pmod_jxadc_n,
    output  wire [3:0]      pmod_jxadc,
    output  wire [3:0]      vga_red_pad,
    input   wire [3:0]      vga_red,
    output  wire [3:0]      vga_blue_pad,
    input   wire [3:0]      vga_blue,
    output  wire [3:0]      vga_green_pad,
    input   wire [3:0]      vga_green,
    output  wire            vga_hsync_pad,
    input   wire            vga_hsync,
    output  wire            vga_vsync_pad,
    input   wire            vga_vsync,
    input   wire            uart_rx_pad,
    output  wire            uart_rx,
    output  wire            uart_tx_pad,
    input   wire            uart_tx,
    inout   wire            ps2_clk_pad,
    output  wire            ps2_clk_i,
    input   wire            ps2_clk_o,
    input   wire            ps2_clk_t,
    inout   wire            ps2_data_pad,
    output  wire            ps2_data_i,
    input   wire            ps2_data_o,
    input   wire            ps2_data_t,
    output  wire            spi_cs_n_pad,
    input   wire            spi_cs_n,
    inout   wire            spi_sdi_pad,
    output  wire            spi_sdi_i,
    input   wire            spi_sdi_o,
    input   wire            spi_sdi_t,
    inout   wire            spi_sdo_pad,
    output  wire            spi_sdo_i,
    input   wire            spi_sdo_o,
    input   wire            spi_sdo_t,
    inout   wire            spi_wp_n_pad,
    output  wire            spi_wp_n_i,
    input   wire            spi_wp_n_o,
    input   wire            spi_wp_n_t,
    inout   wire            spi_hld_n_pad,
    output  wire            spi_hld_n_i,
    input   wire            spi_hld_n_o,
    input   wire            spi_hld_n_t
);

    assign clk_100m00 = clk_100m00_pad;

    assign slider_sw = slider_sw_pad;

    assign led_pad = led;

    assign seg_pad = seg;

    assign digit_en_pad = digit_en;

    assign dp_pad = dp;

    assign btn = btn_pad;

    IBUFDS //#(
    //)
    ibufds_pmod_jxadc_i0 (
        .O  (pmod_jxadc[0]),
        .I  (pmod_jxadc_p[0]),
        .IB (pmod_jxadc_n[0])
    );

    IBUFDS //#(
    //)
    ibufds_pmod_jxadc_i1 (
        .O  (pmod_jxadc[1]),
        .I  (pmod_jxadc_p[1]),
        .IB (pmod_jxadc_n[1])
    );

    IBUFDS //#(
    //)
    ibufds_pmod_jxadc_i2 (
        .O  (pmod_jxadc[2]),
        .I  (pmod_jxadc_p[2]),
        .IB (pmod_jxadc_n[2])
    );

    IBUFDS //#(
    //)
    ibufds_pmod_jxadc_i3 (
        .O  (pmod_jxadc[3]),
        .I  (pmod_jxadc_p[3]),
        .IB (pmod_jxadc_n[3])
    );

    assign vga_red_pad = vga_red;

    assign vga_blue_pad = vga_blue;

    assign vga_green_pad = vga_green;

    assign vga_hsync_pad = vga_hsync;

    assign vga_vsync_pad = vga_vsync;

    IBUF //#(
    //)
    ibuf_uart_rx_i0 (
        .O  (uart_rx),
        .I  (uart_rx_pad)
    );

    OBUF //#(
    //)
    obuf_uart_tx_i0 (
        .O  (uart_tx_pad),
        .I  (uart_tx)
    );

    IOBUF //#(
    //)
    iobuf_ps2_clk_i0 (
        .O  (ps2_clk_i),
        .I  (ps2_clk_o),
        .IO (ps2_clk_pad),
        .T  (ps2_clk_t)
    );

    IOBUF //#(
    //)
    iobuf_ps2_data_i0 (
        .O  (ps2_data_i),
        .I  (ps2_data_o),
        .IO (ps2_data_pad),
        .T  (ps2_data_t)
    );

    OBUF //#(
    //)
    obuf_spi_cs_n_i0 (
        .O  (spi_cs_n_pad),
        .I  (spi_cs_n)
    );

    IOBUF //#(
    //)
    iobuf_spi_sdi_i0 (
        .O  (spi_sdi_i),
        .I  (spi_sdi_o),
        .IO (spi_sdi_pad),
        .T  (spi_sdi_t)
    );

    IOBUF //#(
    //)
    iobuf_spi_sdo_i0 (
        .O  (spi_sdo_i),
        .I  (spi_sdo_o),
        .IO (spi_sdo_pad),
        .T  (spi_sdo_t)
    );

    IOBUF //#(
    //)
    iobuf_spi_wp_n_i0 (
        .O  (spi_wp_n_i),
        .I  (spi_wp_n_o),
        .IO (spi_wp_n_pad),
        .T  (spi_wp_n_t)
    );

    IOBUF //#(
    //)
    iobuf_spi_hld_n_i0 (
        .O  (spi_hld_n_i),
        .I  (spi_hld_n_o),
        .IO (spi_hld_n_pad),
        .T  (spi_hld_n_t)
    );

endmodule
