--
-- Generated by io-gen - do not edit
-- Regenerate from source YAML using io-gen
--
library ieee;
use ieee.std_logic_1164.all;

library unisim;
use unisim.vcomponents.all;

entity basys3_io is
    -- generic (
    -- )
    port (
        clk_100m00_pad  : in    std_logic;
        clk_100m00      : out   std_logic;
        slider_sw_pad   : in    std_logic_vector(15 downto 0);
        slider_sw       : out   std_logic_vector(15 downto 0);
        led_pad         : out   std_logic_vector(15 downto 0);
        led             : in    std_logic_vector(15 downto 0);
        seg_pad         : out   std_logic_vector(6 downto 0);
        seg             : in    std_logic_vector(6 downto 0);
        digit_en_pad    : out   std_logic_vector(3 downto 0);
        digit_en        : in    std_logic_vector(3 downto 0);
        dp_pad          : out   std_logic;
        dp              : in    std_logic;
        btn_pad         : in    std_logic_vector(4 downto 0);
        btn             : out   std_logic_vector(4 downto 0);
        pmod_jxadc_p    : in    std_logic_vector(3 downto 0);
        pmod_jxadc_n    : in    std_logic_vector(3 downto 0);
        pmod_jxadc      : out   std_logic_vector(3 downto 0);
        vga_red_pad     : out   std_logic_vector(3 downto 0);
        vga_red         : in    std_logic_vector(3 downto 0);
        vga_blue_pad    : out   std_logic_vector(3 downto 0);
        vga_blue        : in    std_logic_vector(3 downto 0);
        vga_green_pad   : out   std_logic_vector(3 downto 0);
        vga_green       : in    std_logic_vector(3 downto 0);
        vga_hsync_pad   : out   std_logic;
        vga_hsync       : in    std_logic;
        vga_vsync_pad   : out   std_logic;
        vga_vsync       : in    std_logic;
        uart_rx_pad     : in    std_logic;
        uart_rx         : out   std_logic;
        uart_tx_pad     : out   std_logic;
        uart_tx         : in    std_logic;
        ps2_clk_pad     : inout std_logic;
        ps2_clk_i       : out   std_logic;
        ps2_clk_o       : in    std_logic;
        ps2_clk_t       : in    std_logic;
        ps2_data_pad    : inout std_logic;
        ps2_data_i      : out   std_logic;
        ps2_data_o      : in    std_logic;
        ps2_data_t      : in    std_logic;
        spi_cs_n_pad    : out   std_logic;
        spi_cs_n        : in    std_logic;
        spi_sdi_pad     : inout std_logic;
        spi_sdi_i       : out   std_logic;
        spi_sdi_o       : in    std_logic;
        spi_sdi_t       : in    std_logic;
        spi_sdo_pad     : inout std_logic;
        spi_sdo_i       : out   std_logic;
        spi_sdo_o       : in    std_logic;
        spi_sdo_t       : in    std_logic;
        spi_wp_n_pad    : inout std_logic;
        spi_wp_n_i      : out   std_logic;
        spi_wp_n_o      : in    std_logic;
        spi_wp_n_t      : in    std_logic;
        spi_hld_n_pad   : inout std_logic;
        spi_hld_n_i     : out   std_logic;
        spi_hld_n_o     : in    std_logic;
        spi_hld_n_t     : in    std_logic
    );
end entity basys3_io;

architecture rtl of basys3_io is

begin

    clk_100m00 <= clk_100m00_pad;

    slider_sw <= slider_sw_pad;

    led_pad <= led;

    seg_pad <= seg;

    digit_en_pad <= digit_en;

    dp_pad <= dp;

    btn <= btn_pad;

    ibufds_pmod_jxadc_i0 : IBUFDS
    -- generic map (
    -- )
    port map (
        O   => pmod_jxadc(0),
        I   => pmod_jxadc_p(0),
        IB  => pmod_jxadc_n(0)
    );

    ibufds_pmod_jxadc_i1 : IBUFDS
    -- generic map (
    -- )
    port map (
        O   => pmod_jxadc(1),
        I   => pmod_jxadc_p(1),
        IB  => pmod_jxadc_n(1)
    );

    ibufds_pmod_jxadc_i2 : IBUFDS
    -- generic map (
    -- )
    port map (
        O   => pmod_jxadc(2),
        I   => pmod_jxadc_p(2),
        IB  => pmod_jxadc_n(2)
    );

    ibufds_pmod_jxadc_i3 : IBUFDS
    -- generic map (
    -- )
    port map (
        O   => pmod_jxadc(3),
        I   => pmod_jxadc_p(3),
        IB  => pmod_jxadc_n(3)
    );

    vga_red_pad <= vga_red;

    vga_blue_pad <= vga_blue;

    vga_green_pad <= vga_green;

    vga_hsync_pad <= vga_hsync;

    vga_vsync_pad <= vga_vsync;

    ibuf_uart_rx_i0 : IBUF
    -- generic map (
    -- )
    port map (
        O   => uart_rx,
        I   => uart_rx_pad
    );

    obuf_uart_tx_i0 : OBUF
    -- generic map (
    -- )
    port map (
        O   => uart_tx_pad,
        I   => uart_tx
    );

    iobuf_ps2_clk_i0 : IOBUF
    -- generic map (
    -- )
    port map (
        O   => ps2_clk_i,
        I   => ps2_clk_o,
        IO  => ps2_clk_pad,
        T   => ps2_clk_t
    );

    iobuf_ps2_data_i0 : IOBUF
    -- generic map (
    -- )
    port map (
        O   => ps2_data_i,
        I   => ps2_data_o,
        IO  => ps2_data_pad,
        T   => ps2_data_t
    );

    obuf_spi_cs_n_i0 : OBUF
    -- generic map (
    -- )
    port map (
        O   => spi_cs_n_pad,
        I   => spi_cs_n
    );

    iobuf_spi_sdi_i0 : IOBUF
    -- generic map (
    -- )
    port map (
        O   => spi_sdi_i,
        I   => spi_sdi_o,
        IO  => spi_sdi_pad,
        T   => spi_sdi_t
    );

    iobuf_spi_sdo_i0 : IOBUF
    -- generic map (
    -- )
    port map (
        O   => spi_sdo_i,
        I   => spi_sdo_o,
        IO  => spi_sdo_pad,
        T   => spi_sdo_t
    );

    iobuf_spi_wp_n_i0 : IOBUF
    -- generic map (
    -- )
    port map (
        O   => spi_wp_n_i,
        I   => spi_wp_n_o,
        IO  => spi_wp_n_pad,
        T   => spi_wp_n_t
    );

    iobuf_spi_hld_n_i0 : IOBUF
    -- generic map (
    -- )
    port map (
        O   => spi_hld_n_i,
        I   => spi_hld_n_o,
        IO  => spi_hld_n_pad,
        T   => spi_hld_n_t
    );

end architecture rtl;
