--
-- Generated by io-gen - do not edit
-- Regenerate from source YAML using io-gen
--
library ieee;
use ieee.std_logic_1164.all;

library unisim;
use unisim.vcomponents.all;

entity example_io is
    -- generic (
    -- )
    port (
        sys_clk_pad     : in    std_logic;
        sys_clk         : out   std_logic;
        led_pad         : out   std_logic_vector(3 downto 0);
        led             : in    std_logic_vector(3 downto 0);
        user_led_pad    : out   std_logic;
        user_led        : in    std_logic;
        ref_clk_p       : in    std_logic;
        ref_clk_n       : in    std_logic;
        ref_clk         : out   std_logic;
        lvds_data_p     : out   std_logic_vector(2 downto 0);
        lvds_data_n     : out   std_logic_vector(2 downto 0);
        lvds_data       : in    std_logic_vector(2 downto 0);
        gpio_pad        : inout std_logic_vector(4 downto 0);
        gpio_i          : out   std_logic_vector(4 downto 0);
        gpio_o          : in    std_logic_vector(4 downto 0);
        gpio_t          : in    std_logic_vector(4 downto 0)
    );
end entity example_io;

architecture rtl of example_io is
begin

    ibuf_sys_clk_i0 : IBUF
    -- generic map (
    -- )
    port map (
        O   => sys_clk,
        I   => sys_clk_pad
    );

    obuf_led_i0 : OBUF
    -- generic map (
    -- )
    port map (
        O   => led_pad(0),
        I   => led(0)
    );

    obuf_led_i1 : OBUF
    -- generic map (
    -- )
    port map (
        O   => led_pad(1),
        I   => led(1)
    );

    obuf_led_i2 : OBUF
    -- generic map (
    -- )
    port map (
        O   => led_pad(2),
        I   => led(2)
    );

    obuf_led_i3 : OBUF
    -- generic map (
    -- )
    port map (
        O   => led_pad(3),
        I   => led(3)
    );

    user_led_pad <= user_led;

    ibufds_ref_clk_i0 : IBUFDS
    -- generic map (
    -- )
    port map (
        O   => ref_clk,
        I   => ref_clk_p,
        IB  => ref_clk_n
    );

    obufds_lvds_data_i0 : OBUFDS
    -- generic map (
    -- )
    port map (
        O   => lvds_data_p(0),
        OB  => lvds_data_n(0),
        I   => lvds_data(0)
    );

    obufds_lvds_data_i1 : OBUFDS
    -- generic map (
    -- )
    port map (
        O   => lvds_data_p(1),
        OB  => lvds_data_n(1),
        I   => lvds_data(1)
    );

    obufds_lvds_data_i2 : OBUFDS
    -- generic map (
    -- )
    port map (
        O   => lvds_data_p(2),
        OB  => lvds_data_n(2),
        I   => lvds_data(2)
    );

    iobuf_gpio_i0 : IOBUF
    -- generic map (
    -- )
    port map (
        O   => gpio_i(0),
        I   => gpio_o(0),
        IO  => gpio_pad(0),
        T   => gpio_t(0)
    );

    iobuf_gpio_i1 : IOBUF
    -- generic map (
    -- )
    port map (
        O   => gpio_i(1),
        I   => gpio_o(1),
        IO  => gpio_pad(1),
        T   => gpio_t(1)
    );

    iobuf_gpio_i2 : IOBUF
    -- generic map (
    -- )
    port map (
        O   => gpio_i(2),
        I   => gpio_o(2),
        IO  => gpio_pad(2),
        T   => gpio_t(2)
    );

    iobuf_gpio_i3 : IOBUF
    -- generic map (
    -- )
    port map (
        O   => gpio_i(3),
        I   => gpio_o(3),
        IO  => gpio_pad(3),
        T   => gpio_t(3)
    );

    iobuf_gpio_i4 : IOBUF
    -- generic map (
    -- )
    port map (
        O   => gpio_i(4),
        I   => gpio_o(4),
        IO  => gpio_pad(4),
        T   => gpio_t(4)
    );

end architecture rtl;
