//
// Generated by io-gen - do not edit
// Regenerate from source YAML using io-gen
//
module example_io //#(
//)
(
    input   wire            sys_clk_pad,
    output  wire            sys_clk,
    output  wire [3:0]      led_pad,
    input   wire [3:0]      led,
    output  wire            user_led_pad,
    input   wire            user_led,
    input   wire            ref_clk_p,
    input   wire            ref_clk_n,
    output  wire            ref_clk,
    output  wire [2:0]      lvds_data_p,
    output  wire [2:0]      lvds_data_n,
    input   wire [2:0]      lvds_data,
    inout   wire [4:0]      gpio_pad,
    output  wire [4:0]      gpio_i,
    input   wire [4:0]      gpio_o,
    input   wire [4:0]      gpio_t,
    inout   wire            diff_io_p,
    inout   wire            diff_io_n,
    output  wire            diff_io_i,
    input   wire            diff_io_o,
    input   wire            diff_io_t
);

    IBUF //#(
    //)
    ibuf_sys_clk_i0 (
        .O      (sys_clk),
        .I      (sys_clk_pad)
    );

    OBUF //#(
    //)
    obuf_led_i0 (
        .O      (led_pad[0]),
        .I      (led[0])
    );

    OBUF //#(
    //)
    obuf_led_i1 (
        .O      (led_pad[1]),
        .I      (led[1])
    );

    OBUF //#(
    //)
    obuf_led_i2 (
        .O      (led_pad[2]),
        .I      (led[2])
    );

    OBUF //#(
    //)
    obuf_led_i3 (
        .O      (led_pad[3]),
        .I      (led[3])
    );

    assign user_led_pad = user_led;

    IBUFDS //#(
    //)
    ibufds_ref_clk_i0 (
        .O      (ref_clk),
        .I      (ref_clk_p),
        .IB     (ref_clk_n)
    );

    OBUFDS //#(
    //)
    obufds_lvds_data_i0 (
        .O      (lvds_data_p[0]),
        .OB     (lvds_data_n[0]),
        .I      (lvds_data[0])
    );

    OBUFDS //#(
    //)
    obufds_lvds_data_i1 (
        .O      (lvds_data_p[1]),
        .OB     (lvds_data_n[1]),
        .I      (lvds_data[1])
    );

    OBUFDS //#(
    //)
    obufds_lvds_data_i2 (
        .O      (lvds_data_p[2]),
        .OB     (lvds_data_n[2]),
        .I      (lvds_data[2])
    );

    IOBUF //#(
    //)
    iobuf_gpio_i0 (
        .O      (gpio_i[0]),
        .I      (gpio_o[0]),
        .IO     (gpio_pad[0]),
        .T      (gpio_t[0])
    );

    IOBUF //#(
    //)
    iobuf_gpio_i1 (
        .O      (gpio_i[1]),
        .I      (gpio_o[1]),
        .IO     (gpio_pad[1]),
        .T      (gpio_t[1])
    );

    IOBUF //#(
    //)
    iobuf_gpio_i2 (
        .O      (gpio_i[2]),
        .I      (gpio_o[2]),
        .IO     (gpio_pad[2]),
        .T      (gpio_t[2])
    );

    IOBUF //#(
    //)
    iobuf_gpio_i3 (
        .O      (gpio_i[3]),
        .I      (gpio_o[3]),
        .IO     (gpio_pad[3]),
        .T      (gpio_t[3])
    );

    IOBUF //#(
    //)
    iobuf_gpio_i4 (
        .O      (gpio_i[4]),
        .I      (gpio_o[4]),
        .IO     (gpio_pad[4]),
        .T      (gpio_t[4])
    );

    IOBUFDS //#(
    //)
    iobufds_diff_io_i0 (
        .O      (diff_io_i),
        .I      (diff_io_o),
        .IO     (diff_io_p),
        .IOB    (diff_io_n),
        .T      (diff_io_t)
    );

endmodule
