#!/bin/bash

function log_err () {
    local msg
    msg="${1}"
    printf '%s\n' "${msg}" >&2
}

function usage () {
    cat <<EOF
Usage: $(basename "$0") <part> <xdc_file> <output_dir>

Arguments:
  part      Xilinx part number (e.g. xc7a35tcpg236-1)
  xdc_file  Path to the XDC constraint file to validate
  output_dir   Path to write the DRC reports
EOF
}

# This needs to be run as a command, not sourced into a running subshell
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
    log_err "Script needs to be run as a command, not sourced"
    return 1
fi

# Make sure we can find the Tcl script to run Vivado in
script_name="$(realpath "${0}")"
script_dir="$(dirname "${script_name}")"
if [[ ! -f "${script_dir}/run_drc.tcl" ]]; then
    log_err "Could not find 'run_drc.tcl'"
    exit 1
fi

# Make sure the user has Vivado in the path (i.e., user has sourced the
# appropriate settings file in the Vivado install directory)
command -v vivado >/dev/null 2>&1 || \
    { log_err "Vivado not found in PATH."; exit 1; }

# Parse positional input arguments
if [[ $# -ne 3 ]]; then
    usage
    exit 1
else
    part="${1}"
    xdc_file="$(readlink -f "${2}")"
    output_dir="$(readlink -f "${3}")"
fi

# Validate files and paths
if [[ ! -f "${xdc_file}" || ! -r "${xdc_file}" ]]; then
    log_err "Missing XDC file or file not readable by current user"
    exit 1
fi

if ! mkdir -p "${output_dir}"; then
    log_err "Could not create directory at ${output_dir}"
    exit 1
fi

# Now we're ready to call Vivado in batch mode, with the transcript and journal
# file saved to the output directory
vivado -mode batch \
    -log "${output_dir}/vivado.log" \
    -journal "${output_dir}/vivado.jou" \
    -source "${script_dir}/run_drc.tcl" \
    -tclargs "${part}" "${xdc_file}" "${output_dir}" || \
    { log_err "Vivado returned a non-zero exit value"; exit 1; }

